version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    container_name: morning-compass-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: morning-compass
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - morning-compass-network

  cloud_server:
    container_name: morning-compass-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    ports:
      - "3500:3500"
    environment:
      MY_LOG_LEVEL: info
      MY_LOG_STYLE: Always
      DATABASE_URL: postgresql://postgres:password@db:5432/morning-compass
    depends_on:
      - db
    command: >
      bash -c "./wait-for-it.sh db:5432 -- diesel setup && diesel migration generate users && chmod +x migration-script.sh && ./migration-script.sh && diesel migration run && diesel migration redo && cargo run"
    networks:
      - morning-compass-network

volumes:
  postgres:
    driver: local

networks:
  morning-compass-network:
