services:
  db:
    image: postgres:latest
    restart: always
    container_name: morning-compass-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: morning-compass
    ports:
      - "3400:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  cloud_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/usr/src/morning-compass-rust"
    links:
      - db
    ports:
      - "3500:3500"
    expose:
      - 3500
    environment:
      - MY_LOG_LEVEL=info
      - MY_LOG_STYLE=Always
      - DATABASE_URL=postgresql://postgres:password@db:5432/morning-compass
    command: 'bash -c "/wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"'

volumes:
  postgres:
    driver: local
