-- down.sql
DROP TABLE IF EXISTS workspace_invitations CASCADE;

DROP TABLE IF EXISTS attendance CASCADE;

DROP TABLE IF EXISTS users_citizenships CASCADE;

DROP TABLE IF EXISTS conversation_participants CASCADE;

DROP TABLE IF EXISTS messages CASCADE;

DROP TABLE IF EXISTS conversations CASCADE;

DROP TABLE IF EXISTS workspace_users CASCADE;

DROP TABLE IF EXISTS full_users CASCADE;

DROP TABLE IF EXISTS worker_workspace_data CASCADE;

DROP TABLE IF EXISTS problems CASCADE;

DROP TABLE IF EXISTS tasks CASCADE;

DROP TABLE IF EXISTS tasks_category CASCADE;

DROP TABLE IF EXISTS positions CASCADE;

DROP TABLE IF EXISTS workspaces CASCADE;

DROP TABLE IF EXISTS user_roles CASCADE;

DROP TABLE IF EXISTS workspace_roles CASCADE;

DROP TABLE IF EXISTS phone_dial_codes CASCADE;

DROP TABLE IF EXISTS countries CASCADE;

DROP TABLE IF EXISTS ev_subscriptions CASCADE;

DROP TABLE IF EXISTS status CASCADE;

DROP TABLE IF EXISTS importance CASCADE;

DROP TABLE IF EXISTS password_reset_tokens CASCADE;

DROP TABLE IF EXISTS confirmation_tokens CASCADE;

DROP TABLE IF EXISTS auth_users CASCADE;

DROP TABLE IF EXISTS roles CASCADE;
